# Site
repository: https://emehra1.github.io/
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Eshan Mehra
title: Harvard University — A.B., Chemistry, Physics, and Human Developmental & Regenerative Biology (Expected May 2027)

# Dark Mode (true/false/never)
darkmode: true


# Social links
linkedin_username: eshan-mehra-86aa26201
twitter_username: emehra30
googlescholar_username: "nJMnE9EAAAAJ&hl=en"
github_username: emehra1

# Additional icon links
additional_links:
  - title: Email
    icon: fas fa-envelope
    url: mailto:emehra@broadinstitute.org
  - title: Substack
    icon: fas fa-pencil-alt
    url: https://eshanmehra.substack.com/

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://esmehra1.github.io/)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Eshan Mehra
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Building and leveraging next-generation omics tools to uncover new levers to reprogram cell fate and restore resilience across the lifespan.

content:
  - title: Research Experience
    layout: list
    content:
      - layout: left
        title: Buenrostro Lab @ Broad Institute of MIT and Harvard
        sub_title: Research Fellow
        caption: May 2025 – Present
        description: |

          Engineering a cost-effective, high-throughput single-cell methylation sequencing assay.

      - layout: left
        title: Synthetic Immunity Lab @ Harvard Medical School (Dana-Farber Cancer Institute)
        sub_title: Research Fellow
        caption: November 2023 – January 2025
        description: |
          Designed and constructed cancer-targeting synthetic gene circuits to enhance the efficacy, specificity, and persistence of combinatorial immunotherapy.

          Programmed T-cells with logic-gated induction of an immortalized "zombie T-cell" (zT-cell) state to overcome T-cell exhaustion in vivo.

          Characterized dynamics of immortalized T cells in vivo and in vitro.

          Mentored by Dr. Ming-Ru Wu, Dept. of Cancer Immunology & Virology.

      - layout: left
        title: Gao Lab @ Northwestern University Feinberg School of Medicine (Lurie’s Cancer Center)
        sub_title: Research Fellow
        caption: May 2023 – August 2023
        description: |
          Employed Nanopore scRNA-seq on patient-matched renal cell carcinoma primary tumors and brain metastases to map targetable cell types and markers for metastasis prevention.

          Analyzed tumor and immune cell gene-expression dynamics during brain-metastasis evolution.

          Awarded 1st Place Poster Presentation by the Beckman Institute of Advanced Science and Technology.

  - title: Leadership and Extracurriculars
    layout: list
    content:
      - layout: left
        title: TIME Initiative
        sub_title: Fellow; Director of TIME Cast
        caption: March 2025 – Present
        description: |
          Selected as 1 of 25 fellows supported by the Academy for Health & Lifespan Research; represent youth in aging biology at major conferences across the world; network with pioneers in aging biology biotech, academia, and venture capital; host podcast episodes with leaders in aging biology.

      - layout: left
        title: Nexus Fellowship (Norn Group)
        sub_title: Fellow
        caption: February 2025 – Present
        description: |
          Drive translational efforts in age-related disease by leading journal clubs, drafting policy memos, and designing/securing funding for novel experiments.

      - layout: left
        title: Future of Aging Summit
        sub_title: Co-Founder and Co-Host
        caption: January 2024 – Present
        description: |
          Hosting an interdisciplinary summit on aging at the annual Gerontological Society of America (GSA) 2025 with expected 100+ attendees; leading and hosting Clinical Research in Aging and Biotech’s Role in Aging Panel

      - layout: left
        title: Aging Initiative at Harvard
        sub_title: Vice President of Partnerships
        caption: October 2023 – Present
        description: |
          Spearheaded the Muscle Aging Science and Translation (MAST) Symposium (April 2024), the largest muscle aging conference in the world including speakers David Glass, Andrew Adams, Anne-Ulrike Trendelenburg and Boston’s largest aging-biology mixer (Nov 2024) including speakers George Church, Alex Colville, and Jesse Poganik.

          Co-lead a team of 27; manage partnerships with other companies and advisory board members including George Church, Martin Borch Jensen, Laza Nuzhna, and Jake Becraft; raised $10,000+ through industry outreach.

          Lead professor-dinner series and events with MIT/Harvard researchers (e.g., Jonathan Gootenberg, Omar Abudayyeh).

      - layout: left
        title: Global Alliance for Medical Innovation (GAMI)
        sub_title: Research & Development Co-Lead
        caption: February 2024 – Present
        description: |
          Building a nurse-patient matching mobile app for elderly patients in rural India with Udaya Kumar and ISER Tirupati partners; mapping delivery bottlenecks and spearheading pilot implementation.

      - layout: left
        title: Nucleate Aging Biology Thematic Series
        sub_title: Co-Lead
        caption: August 2024 – May 2025
        description: |
          Co-founded and led a global thematic series; hosted panel focused on startups and venture capital in longevity biotech with Joshua Olshavsky, Steve Robinette, Alex Colville, and Lada Nuzhna

          Authored resource guides accompanying panel discussions.

      - layout: left
        title: Harvard OpenBio
        sub_title: Biosecurity Team Co-Lead & Co-Founder
        caption: February 2024 – January 2025
        description: |
          Organized biosecurity journal club and speaker sessions; planned and co-hosted the Future of Biology Conference (130+ attendees; keynotes: George Church, Reshma Shetty).

          Co-led the Harvard Summer Research Institute, matching 73 underserved students to research mentors and publishing their abstracts.

  - title: Honors and Awards
    layout: text
    content: |
      - TIME x Aoki Foundation Grant Recipient - 1 of 11 recipients; support from TIME Initiative and Aoki Foundation to host Immune Aging Speaker series. 2026
      - John Harvard Scholar (top 5% of class). 2025
      - TIME Initiative Exploration Grant — 1 of 4 recipients; support from TIME Initiative and age1 VC to represent next-gen leaders at ARDD 2025 (Copenhagen). 2025
      - Herchel-Smith Fellow — Competitive fellowship supporting independent research in the Buenrostro Lab (Broad Institute); received travel grant to present at ARDD. 2025
      - PRISE (Program for Research in Science & Engineering) Fellow, Harvard Office of Undergraduate Research & Fellowships. 2024
      - Harvard College Research Program (HCRP) Grants (Twice Awarded). 2024
      - Congressional Award — Bronze Medalist, United States Congress. 2022
      - Jessie Chambers Scholarship, National Junior Classical League — 1 of 8 national recipients ($1,500). 2023
      - National Latin Exam Scholarship, NLE Scholarship Committee — 1 of 12 global recipients ($2,000). 2023

  - title: Publications and Presentations
    layout: text
    content: |
      - Dasariraju, S., Simonini, S., **Mehra, E.**, Fedorovskyy, M., Law, C., Khera, N., Rajagopal, K., & Orkaby, A. (2025). Aging Initiative: A Student-Led Model for Advancing Aging Research with a Translational Focus. Late-breaking poster presented at the Gerontological Society of America (GSA) Annual Scientific Meeting, Cambridge, MA.
      - Chan, K., Wang, J., Balakumar, A., Ng, M., **Mehra, E.**, Jain, L., Fischetti, C., Foody, J.N., Duggan, N.M., Goldsmith, A.J., & Allan-Blitz, L.-T. (2025). Using Machine Learning to Classify Manifestations of Extrapulmonary Tuberculosis with Point-of-Care Ultrasound: A Proof of Concept. The Ultrasound Journal. (under review).
      - **Mehra, E.**, Lu, L., Lin, H.-Y., Shiau, C.-K., Pan, T., & Gao, R. (2023). Delineating Cellular Ecosystem Dynamics from Renal Cell Carcinomas to Brain Metastases. Poster presented at the Lurie Cancer Research Center, Northwestern University Feinberg School of Medicine, Chicago, IL and Harvard University, Cambridge, MA.
      - Emani, V., An, D., **Mehra, E.** (2025). A Digital Platform to Improve Access & Affordability of Trained Homecare Medical Nurses in India. Poster presented at Harvard University, Cambridge, MA.
      - **Mehra, E.** How the Power Shift in Healthcare from Providers to Insurers is Eroding Physician–Patient Relationships. 2023.

  - title: Projects
    layout: text
    content: |
      - Modeling IL-2 + Adoptive Cellular Immunotherapy in Tumor Growth (2024) — Built and analyzed a systems model exploring dosing synergies between IL-2 and ACI to study tumor-growth dynamics.

  - title: Skills
    layout: text
    content: |
      - Laboratory: molecular cloning; lentiviral transfection & transduction; mammalian cell culture; miniprep; PCR & gel electrophoresis; bacterial transformation & plating; colony selection & liquid cultures; imaging; Seurat; mouse handling.
      - Technical: Python; R; Command Line; MATLAB; Mathematica; LaTeX.
      - Other Activities: Harvard Hindu Association; Harvard Cycling Club; Harvard Undergraduate Health Policy Review (Senior Editor).

  - title: Hobbies
    layout: text
    content: |
      - Cycling
      - Running
      - Biotech
      - Formula 1
  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - lib/
  - scripts/
  - docker-compose.yml